/**
 * Proposal Management Constants
 *
 * Status options and configuration for the admin proposal management tool.
 * Merged from external tool types/proposal.js and existing proposalStatusConfig.js
 */

import { PROPOSAL_STATUSES as CANONICAL_STATUSES } from '../../../logic/constants/proposalStatuses.js';

/**
 * All possible proposal statuses in the system
 * Used for status dropdown and filtering
 */
export const PROPOSAL_STATUSES = [
  CANONICAL_STATUSES.SUGGESTED_PROPOSAL_AWAITING_RENTAL_APP.key,
  CANONICAL_STATUSES.PROPOSAL_SUBMITTED_AWAITING_RENTAL_APP.key,
  CANONICAL_STATUSES.SUGGESTED_PROPOSAL_PENDING_CONFIRMATION.key,
  CANONICAL_STATUSES.HOST_REVIEW.key,
  CANONICAL_STATUSES.COUNTEROFFER_SUBMITTED_AWAITING_GUEST_REVIEW.key,
  'Guest Counteroffer Submitted / Awaiting Host Review',
  CANONICAL_STATUSES.PROPOSAL_OR_COUNTEROFFER_ACCEPTED.key,
  CANONICAL_STATUSES.LEASE_DOCUMENTS_SENT_FOR_REVIEW.key,
  CANONICAL_STATUSES.LEASE_DOCUMENTS_SENT_FOR_SIGNATURES.key,
  CANONICAL_STATUSES.LEASE_DOCUMENTS_SIGNED_AWAITING_PAYMENT.key,
  CANONICAL_STATUSES.INITIAL_PAYMENT_SUBMITTED_LEASE_ACTIVATED.key,
  CANONICAL_STATUSES.CANCELLED_BY_GUEST.key,
  CANONICAL_STATUSES.REJECTED_BY_HOST.key,
  CANONICAL_STATUSES.CANCELLED_BY_SPLITLEASE.key,
  'Guest Ignored Suggestion'
];

/**
 * Days of the week abbreviations
 * Uses 0-indexed format matching JavaScript Date.getDay()
 */
export const DAYS_OF_WEEK = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];

/**
 * Full day names
 */
export const DAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

/**
 * Default proposal status for admin-created proposals
 */
export const DEFAULT_ADMIN_PROPOSAL_STATUS = CANONICAL_STATUSES.SUGGESTED_PROPOSAL_AWAITING_RENTAL_APP.key;

/**
 * Statuses that indicate a proposal is active/in-progress
 */
export const ACTIVE_STATUSES = [
  CANONICAL_STATUSES.SUGGESTED_PROPOSAL_AWAITING_RENTAL_APP.key,
  CANONICAL_STATUSES.PROPOSAL_SUBMITTED_AWAITING_RENTAL_APP.key,
  CANONICAL_STATUSES.SUGGESTED_PROPOSAL_PENDING_CONFIRMATION.key,
  CANONICAL_STATUSES.HOST_REVIEW.key,
  CANONICAL_STATUSES.COUNTEROFFER_SUBMITTED_AWAITING_GUEST_REVIEW.key,
  'Guest Counteroffer Submitted / Awaiting Host Review',
  CANONICAL_STATUSES.PROPOSAL_OR_COUNTEROFFER_ACCEPTED.key,
  CANONICAL_STATUSES.LEASE_DOCUMENTS_SENT_FOR_REVIEW.key,
  CANONICAL_STATUSES.LEASE_DOCUMENTS_SENT_FOR_SIGNATURES.key,
  CANONICAL_STATUSES.LEASE_DOCUMENTS_SIGNED_AWAITING_PAYMENT.key
];

/**
 * Statuses that indicate a proposal is closed/completed
 */
export const CLOSED_STATUSES = [
  CANONICAL_STATUSES.INITIAL_PAYMENT_SUBMITTED_LEASE_ACTIVATED.key,
  CANONICAL_STATUSES.CANCELLED_BY_GUEST.key,
  CANONICAL_STATUSES.REJECTED_BY_HOST.key,
  CANONICAL_STATUSES.CANCELLED_BY_SPLITLEASE.key,
  'Guest Ignored Suggestion'
];

/**
 * Statuses that indicate a lease has been created for the proposal
 * Used to determine if "View My Lease" button should be shown
 */
export const LEASE_CREATED_STATUSES = [
  CANONICAL_STATUSES.PROPOSAL_OR_COUNTEROFFER_ACCEPTED.key,
  CANONICAL_STATUSES.LEASE_DOCUMENTS_SENT_FOR_REVIEW.key,
  CANONICAL_STATUSES.LEASE_DOCUMENTS_SENT_FOR_SIGNATURES.key,
  CANONICAL_STATUSES.LEASE_DOCUMENTS_SIGNED_AWAITING_PAYMENT.key,
  CANONICAL_STATUSES.INITIAL_PAYMENT_SUBMITTED_LEASE_ACTIVATED.key
];
