/**
 * Authentication Fixtures for E2E Tests
 *
 * Provides authenticated browser contexts for different user types.
 * Uses pre-generated storage states from e2e/.auth/ directory.
 *
 * Storage states are generated by global-setup.ts before tests run.
 *
 * Available fixtures:
 * - guestBigSpenderPage: Page with Big Spender guest logged in
 * - guestHighFlexPage: Page with High Flexibility guest logged in
 * - guestAveragePage: Page with Average guest logged in
 * - hostPage: Page with Host user logged in
 * - anonymousPage: Page with no authentication
 */

import { test as base, expect, Page, BrowserContext } from '@playwright/test';
import * as path from 'path';
import { fileURLToPath } from 'url';

// ES Module compatible __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ============================================================================
// TYPES
// ============================================================================

interface AuthFixtures {
  /** Page with Big Spender guest logged in */
  guestBigSpenderPage: Page;
  /** Page with High Flexibility guest logged in */
  guestHighFlexPage: Page;
  /** Page with Average guest logged in */
  guestAveragePage: Page;
  /** Page with Host user logged in */
  hostPage: Page;
  /** Page with Admin user logged in */
  adminPage: Page;
  /** Page with no authentication */
  anonymousPage: Page;
  /** Authenticated context for Big Spender guest */
  guestBigSpenderContext: BrowserContext;
  /** Authenticated context for Host */
  hostContext: BrowserContext;
}

// ============================================================================
// STORAGE STATE PATHS
// ============================================================================

const AUTH_DIR = path.join(__dirname, '..', '.auth');

const STORAGE_STATES = {
  guestBigSpender: path.join(AUTH_DIR, 'guest-big-spender.json'),
  guestHighFlex: path.join(AUTH_DIR, 'guest-high-flex.json'),
  guestAverage: path.join(AUTH_DIR, 'guest-average.json'),
  host: path.join(AUTH_DIR, 'host.json'),
  admin: path.join(AUTH_DIR, 'admin.json')
};

// ============================================================================
// EXTENDED TEST WITH AUTH FIXTURES
// ============================================================================

/**
 * Extended test object with authentication fixtures
 *
 * Usage:
 * ```typescript
 * import { test, expect } from '../fixtures/auth';
 *
 * test('should display user dashboard', async ({ guestBigSpenderPage }) => {
 *   await guestBigSpenderPage.goto('/guest-leases');
 *   await expect(guestBigSpenderPage.locator('[data-testid="lease-card"]')).toBeVisible();
 * });
 * ```
 */
export const test = base.extend<AuthFixtures>({
  /**
   * Page with Big Spender guest logged in
   * Has 'big_spender' archetype with high confidence
   */
  guestBigSpenderPage: async ({ browser }, use) => {
    const context = await browser.newContext({
      storageState: STORAGE_STATES.guestBigSpender
    });
    const page = await context.newPage();
    await use(page);
    await context.close();
  },

  /**
   * Page with High Flexibility guest logged in
   * Has 'high_flex' archetype
   */
  guestHighFlexPage: async ({ browser }, use) => {
    const context = await browser.newContext({
      storageState: STORAGE_STATES.guestHighFlex
    });
    const page = await context.newPage();
    await use(page);
    await context.close();
  },

  /**
   * Page with Average guest logged in
   * Has 'average' archetype (default)
   */
  guestAveragePage: async ({ browser }, use) => {
    const context = await browser.newContext({
      storageState: STORAGE_STATES.guestAverage
    });
    const page = await context.newPage();
    await use(page);
    await context.close();
  },

  /**
   * Page with Host user logged in
   * Can manage listings and respond to proposals
   */
  hostPage: async ({ browser }, use) => {
    const context = await browser.newContext({
      storageState: STORAGE_STATES.host
    });
    const page = await context.newPage();
    await use(page);
    await context.close();
  },

  /**
   * Page with Admin user logged in
   * Has admin privileges for thread management
   */
  adminPage: async ({ browser }, use) => {
    const context = await browser.newContext({
      storageState: STORAGE_STATES.admin
    });
    const page = await context.newPage();
    await use(page);
    await context.close();
  },

  /**
   * Page with no authentication
   * For testing anonymous user flows
   */
  anonymousPage: async ({ browser }, use) => {
    const context = await browser.newContext();
    const page = await context.newPage();
    await use(page);
    await context.close();
  },

  /**
   * Authenticated context for Big Spender guest
   * Use when you need to create multiple pages with same auth
   */
  guestBigSpenderContext: async ({ browser }, use) => {
    const context = await browser.newContext({
      storageState: STORAGE_STATES.guestBigSpender
    });
    await use(context);
    await context.close();
  },

  /**
   * Authenticated context for Host
   * Use when you need to create multiple pages with same auth
   */
  hostContext: async ({ browser }, use) => {
    const context = await browser.newContext({
      storageState: STORAGE_STATES.host
    });
    await use(context);
    await context.close();
  }
});

// ============================================================================
// RE-EXPORTS
// ============================================================================

export { expect };

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Wait for the page to be fully loaded and authenticated
 * Checks for auth indicators in the UI
 */
export async function waitForAuth(page: Page, timeout: number = 10000): Promise<boolean> {
  try {
    // Wait for any auth indicator to appear
    await page.waitForSelector(
      '.logged-in-avatar, [data-testid="user-avatar"], [data-testid="user-menu"], .user-menu',
      { timeout }
    );
    return true;
  } catch {
    // Check localStorage as fallback
    const hasToken = await page.evaluate(() => {
      return !!(
        localStorage.getItem('splitlease_auth_token') ||
        Object.keys(localStorage).some(key => key.includes('supabase') && key.includes('auth'))
      );
    });
    return hasToken;
  }
}

/**
 * Clear authentication state from a page
 * Useful for testing logout flows
 */
export async function clearAuth(page: Page): Promise<void> {
  await page.evaluate(() => {
    // Clear all auth-related localStorage items
    const keysToRemove = Object.keys(localStorage).filter(key =>
      key.includes('splitlease') ||
      key.includes('supabase') ||
      key.includes('auth')
    );
    keysToRemove.forEach(key => localStorage.removeItem(key));

    // Clear session storage
    sessionStorage.clear();
  });

  // Reload to apply changes
  await page.reload();
}
