openapi: 3.0.3
info:
  title: Split Lease Auth User API
  description: |
    Authentication Edge Function for Split Lease marketplace.
    Handles user authentication, registration, and account management.

    All requests use the action-based pattern: `{ action, payload }`.

    ## Security Note
    These are authentication endpoints - they do NOT require authentication
    (you can't require auth to log in!). Validation is handled within each action.
  version: 1.0.0
  contact:
    name: Split Lease Engineering

servers:
  - url: https://{project-ref}.supabase.co/functions/v1
    description: Supabase Edge Functions

paths:
  /auth-user:
    post:
      summary: Authentication Operations
      description: All authentication operations via action-based routing
      operationId: authUserAction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/LoginRequest'
                - $ref: '#/components/schemas/SignupRequest'
                - $ref: '#/components/schemas/LogoutRequest'
                - $ref: '#/components/schemas/ValidateRequest'
                - $ref: '#/components/schemas/RequestPasswordResetRequest'
                - $ref: '#/components/schemas/UpdatePasswordRequest'
                - $ref: '#/components/schemas/GenerateMagicLinkRequest'
                - $ref: '#/components/schemas/OAuthSignupRequest'
                - $ref: '#/components/schemas/OAuthLoginRequest'
                - $ref: '#/components/schemas/SendMagicLinkSmsRequest'
                - $ref: '#/components/schemas/VerifyEmailRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    # =========================================================================
    # REQUEST SCHEMAS
    # =========================================================================

    LoginRequest:
      type: object
      required:
        - action
        - payload
      properties:
        action:
          type: string
          enum: [login]
        payload:
          $ref: '#/components/schemas/LoginPayload'
      example:
        action: login
        payload:
          email: "user@example.com"
          password: "securepassword"

    LoginPayload:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          minLength: 4

    SignupRequest:
      type: object
      required:
        - action
        - payload
      properties:
        action:
          type: string
          enum: [signup]
        payload:
          $ref: '#/components/schemas/SignupPayload'
      example:
        action: signup
        payload:
          email: "newuser@example.com"
          password: "securepassword"
          retype: "securepassword"
          additionalData:
            firstName: "John"
            lastName: "Doe"
            userType: "Guest"
            phoneNumber: "+1234567890"

    SignupPayload:
      type: object
      required:
        - email
        - password
        - retype
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          minLength: 4
        retype:
          type: string
          format: password
          description: Must match password
        additionalData:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string
            userType:
              type: string
              enum: [Host, Guest]
              default: Guest
            birthDate:
              type: string
              format: date
              description: ISO format YYYY-MM-DD
            phoneNumber:
              type: string

    LogoutRequest:
      type: object
      required:
        - action
        - payload
      properties:
        action:
          type: string
          enum: [logout]
        payload:
          type: object
          description: Empty object (logout is client-side)

    ValidateRequest:
      type: object
      required:
        - action
        - payload
      properties:
        action:
          type: string
          enum: [validate]
        payload:
          type: object
          required:
            - access_token
          properties:
            access_token:
              type: string
              description: JWT access token to validate

    RequestPasswordResetRequest:
      type: object
      required:
        - action
        - payload
      properties:
        action:
          type: string
          enum: [request_password_reset]
        payload:
          type: object
          required:
            - email
          properties:
            email:
              type: string
              format: email
      example:
        action: request_password_reset
        payload:
          email: "user@example.com"

    UpdatePasswordRequest:
      type: object
      required:
        - action
        - payload
      properties:
        action:
          type: string
          enum: [update_password]
        payload:
          type: object
          required:
            - access_token
            - new_password
          properties:
            access_token:
              type: string
              description: Token from password reset link
            new_password:
              type: string
              format: password
              minLength: 4

    GenerateMagicLinkRequest:
      type: object
      required:
        - action
        - payload
      properties:
        action:
          type: string
          enum: [generate_magic_link]
        payload:
          type: object
          required:
            - email
          properties:
            email:
              type: string
              format: email
            redirect_to:
              type: string
              format: uri
              description: URL to redirect after magic link click

    OAuthSignupRequest:
      type: object
      required:
        - action
        - payload
      properties:
        action:
          type: string
          enum: [oauth_signup]
        payload:
          type: object
          required:
            - provider
            - provider_user_id
            - email
          properties:
            provider:
              type: string
              enum: [google, apple, facebook]
            provider_user_id:
              type: string
            email:
              type: string
              format: email
            firstName:
              type: string
            lastName:
              type: string
            profile_photo:
              type: string
              format: uri

    OAuthLoginRequest:
      type: object
      required:
        - action
        - payload
      properties:
        action:
          type: string
          enum: [oauth_login]
        payload:
          type: object
          required:
            - provider
            - provider_user_id
            - email
          properties:
            provider:
              type: string
              enum: [google, apple, facebook]
            provider_user_id:
              type: string
            email:
              type: string
              format: email

    SendMagicLinkSmsRequest:
      type: object
      required:
        - action
        - payload
      properties:
        action:
          type: string
          enum: [send_magic_link_sms]
        payload:
          type: object
          required:
            - phone_number
          properties:
            phone_number:
              type: string
              description: Phone number to send SMS
            redirect_to:
              type: string
              format: uri

    VerifyEmailRequest:
      type: object
      required:
        - action
        - payload
      properties:
        action:
          type: string
          enum: [verify_email]
        payload:
          type: object
          required:
            - token
          properties:
            token:
              type: string
              description: Email verification token

    # =========================================================================
    # RESPONSE SCHEMAS
    # =========================================================================

    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          enum: [true]
        data:
          oneOf:
            - $ref: '#/components/schemas/LoginResponse'
            - $ref: '#/components/schemas/SignupResponse'
            - $ref: '#/components/schemas/ValidateResponse'
            - $ref: '#/components/schemas/PasswordResetResponse'
            - $ref: '#/components/schemas/MagicLinkResponse'

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          enum: [false]
        error:
          type: string

    LoginResponse:
      type: object
      properties:
        access_token:
          type: string
          description: JWT access token
        refresh_token:
          type: string
          description: JWT refresh token
        expires_in:
          type: integer
          description: Token expiry in seconds
        user_id:
          type: string
          description: Application user ID (Bubble-style)
        supabase_user_id:
          type: string
          description: Supabase Auth user UUID
        user_type:
          type: string
          enum: [Host, Guest]
        host_account_id:
          type: string
          description: Legacy host account ID (same as user_id)
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string
        profilePhoto:
          type: string
          format: uri
          nullable: true

    SignupResponse:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        expires_in:
          type: integer
        user_id:
          type: string
          description: Generated Bubble-style user ID
        host_account_id:
          type: string
          description: Same as user_id (legacy compatibility)
        supabase_user_id:
          type: string
        user_type:
          type: string
          enum: [Host, Guest]

    ValidateResponse:
      type: object
      properties:
        valid:
          type: boolean
        user_id:
          type: string
        email:
          type: string
        user_type:
          type: string
        expires_at:
          type: string
          format: date-time

    PasswordResetResponse:
      type: object
      properties:
        message:
          type: string
          description: Always returns success (prevents email enumeration)
      example:
        message: "If an account exists with this email, a password reset link has been sent."

    MagicLinkResponse:
      type: object
      properties:
        magic_link:
          type: string
          format: uri
          description: Generated magic link URL
        expires_at:
          type: string
          format: date-time

# =========================================================================
# ACTION AUTHENTICATION MATRIX
# =========================================================================
# Action                  | Auth Required | Notes
# ------------------------|---------------|----------------------------------
# login                   | No            | Authenticates user
# signup                  | No            | Creates new user
# logout                  | No            | Client-side operation
# validate                | No            | Validates provided token
# request_password_reset  | No            | Sends reset email
# update_password         | No            | Uses reset token
# generate_magic_link     | No            | Internal service
# oauth_signup            | No            | OAuth flow
# oauth_login             | No            | OAuth flow
# send_magic_link_sms     | No            | SMS authentication
# verify_email            | No            | Uses verification token
#
# NOTE: All auth actions are public by design - they ARE the auth endpoints
