#!/usr/bin/env node
/**
 * SYSTEM: Auto-generate documentation from source code
 * This ensures documentation matches reality.
 *
 * Run in CI to update docs automatically.
 *
 * Usage:
 *   node scripts/generate-docs.js
 *
 * What it generates:
 *   - supabase/FUNCTIONS.md (Edge Functions list)
 *   - app/PAGES.md (Page components list)
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ==================================================================
// Generate Edge Functions Documentation
// ==================================================================
function generateEdgeFunctionsDocs() {
  const functionsDir = path.join(__dirname, '..', 'supabase', 'functions');

  if (!fs.existsSync(functionsDir)) {
    console.warn('⚠️  Functions directory not found:', functionsDir);
    return;
  }

  const functions = fs.readdirSync(functionsDir, { withFileTypes: true })
    .filter(d => d.isDirectory() && !d.name.startsWith('_'))
    .filter(d => fs.existsSync(path.join(functionsDir, d.name, 'index.ts')))
    .map(d => {
      const indexPath = path.join(functionsDir, d.name, 'index.ts');
      const content = fs.readFileSync(indexPath, 'utf8');

      // Extract first comment as description
      const commentMatch = content.match(/\/\*\*([\s\S]*?)\*\//);
      let description = 'No description';

      if (commentMatch) {
        description = commentMatch[1]
          .split('\n')
          .map(line => line.replace(/^\s*\*\s?/, '').trim())
          .filter(line => line && !line.startsWith('@'))
          .join(' ')
          .slice(0, 200);
      }

      return {
        name: d.name,
        description,
      };
    })
    .sort((a, b) => a.name.localeCompare(b.name));

  const content = `# Edge Functions Reference

> ⚠️ **This file is auto-generated.** Do not edit manually.
> Run \`node scripts/generate-docs.js\` to update.

**Total Functions:** ${functions.length}
**Last Updated:** ${new Date().toISOString()}
**Generator:** \`scripts/generate-docs.js\`

---

## Functions List

| Function | Description |
|----------|-------------|
${functions.map(f => `| \`${f.name}\` | ${f.description} |`).join('\n')}

---

## Adding a New Function

1. Create directory: \`supabase/functions/your-function/\`
2. Create \`index.ts\` with JSDoc comment
3. Run: \`node scripts/generate-docs.js\`
4. Add to \`supabase/config.toml\`: \`node supabase/scripts/sync-edge-functions.js --fix\`
5. Commit both files

## Deployment

\`\`\`bash
# Deploy single function
supabase functions deploy your-function

# Deploy all functions
supabase functions deploy
\`\`\`

---

*Generated by CI/CD automation*
`;

  const outputPath = path.join(__dirname, '..', 'supabase', 'FUNCTIONS.md');
  fs.writeFileSync(outputPath, content);

  console.log(`✅ Generated Edge Functions docs: ${functions.length} functions`);
  console.log(`   ${outputPath}`);
}

// ==================================================================
// Generate Page Components Documentation
// ==================================================================
function generatePagesDocs() {
  const pagesDir = path.join(__dirname, '..', 'app', 'src', 'islands', 'pages');

  if (!fs.existsSync(pagesDir)) {
    console.warn('⚠️  Pages directory not found:', pagesDir);
    return;
  }

  const pages = fs.readdirSync(pagesDir, { withFileTypes: true })
    .filter(d => d.isDirectory() || (d.isFile() && d.name.endsWith('.jsx')))
    .map(d => {
      const name = d.isDirectory() ? d.name : d.name.replace('.jsx', '');
      const filePath = d.isDirectory()
        ? path.join(pagesDir, d.name, `${d.name}.jsx`)
        : path.join(pagesDir, d.name);

      let description = 'No description';
      let route = 'Unknown';

      if (fs.existsSync(filePath)) {
        const content = fs.readFileSync(filePath, 'utf8');

        // Extract JSDoc comment
        const commentMatch = content.match(/\/\*\*([\s\S]*?)\*\//);
        if (commentMatch) {
          description = commentMatch[1]
            .split('\n')
            .find(line => !line.includes('@') && line.trim())
            ?.replace(/^\s*\*\s?/, '')
            .trim() || description;
        }

        // Try to find route from comment
        const routeMatch = content.match(/@route\s+(.+)/);
        if (routeMatch) {
          route = routeMatch[1].trim();
        }
      }

      return { name, description, route };
    })
    .sort((a, b) => a.name.localeCompare(b.name));

  const content = `# Page Components Reference

> ⚠️ **This file is auto-generated.** Do not edit manually.
> Run \`node scripts/generate-docs.js\` to update.

**Total Pages:** ${pages.length}
**Last Updated:** ${new Date().toISOString()}

---

## Pages

| Page Component | Route | Description |
|----------------|-------|-------------|
${pages.map(p => `| \`${p.name}\` | \`${p.route}\` | ${p.description} |`).join('\n')}

---

## Adding a New Page

1. Create HTML: \`app/public/your-page.html\`
2. Create entry: \`app/src/your-page.jsx\`
3. Create component: \`app/src/islands/pages/YourPage/\`
4. Add to routes: \`app/src/routes.config.js\`
5. Run: \`bun run generate-routes\`
6. Run: \`node scripts/generate-docs.js\`

---

*Generated by CI/CD automation*
`;

  const outputPath = path.join(__dirname, '..', 'app', 'PAGES.md');
  fs.writeFileSync(outputPath, content);

  console.log(`✅ Generated Pages docs: ${pages.length} pages`);
  console.log(`   ${outputPath}`);
}

// ==================================================================
// Main Execution
// ==================================================================
console.log('📚 Generating documentation from source code...');
console.log('');

generateEdgeFunctionsDocs();
generatePagesDocs();

console.log('');
console.log('✅ Documentation generation complete!');
console.log('');
console.log('📝 Generated files:');
console.log('   - supabase/FUNCTIONS.md');
console.log('   - app/PAGES.md');
console.log('');
