/**
 * Process Virtual Meeting Handler
 * Split Lease - Supabase Edge Functions
 *
 * Main workflow handler for calendar automation.
 * Migrated from Python/Flask routes.py bubble_trigger endpoint.
 *
 * NO FALLBACK PRINCIPLE: All errors fail fast without fallback logic
 */

import { SupabaseClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { ValidationError, SupabaseSyncError } from '../../_shared/errors.ts';
import type {
  ProcessVirtualMeetingPayload,
  ProcessVirtualMeetingResponse,
  VirtualMeetingRecord,
  VirtualMeetingUpdate,
} from '../lib/types.ts';
import { validateProcessVirtualMeetingInput, validateVirtualMeetingRecord, validateDateTime } from '../lib/validators.ts';
import { GoogleCalendarService } from '../lib/googleCalendarService.ts';

/**
 * Handle process virtual meeting request
 *
 * Workflow (migrated from Python bubble_trigger):
 * 1. Validate input (virtualMeetingId)
 * 2. Fetch virtual meeting record from database
 * 3. Validate record is confirmed and has required fields
 * 4. Normalize dates to ISO 8601
 * 5. Create team calendar event with Meet link
 * 6. Extract Meet link from team event
 * 7. Update virtual meeting with Meet link and status
 * 8. Create guest calendar event with existing Meet link
 * 9. Create host calendar event with existing Meet link
 * 10. Update virtual meeting with event IDs and flags
 */
export async function handleProcessVirtualMeeting(
  payload: Record<string, unknown>,
  _user: unknown,
  supabase: SupabaseClient
): Promise<ProcessVirtualMeetingResponse['data']> {
  console.log('[calendar-automation:process] Starting process virtual meeting');

  // ================================================
  // STEP 1: VALIDATE INPUT
  // ================================================

  validateProcessVirtualMeetingInput(payload);
  const { virtualMeetingId } = payload as ProcessVirtualMeetingPayload;

  console.log(`[calendar-automation:process] Processing virtual meeting: ${virtualMeetingId}`);

  // ================================================
  // STEP 2: FETCH VIRTUAL MEETING RECORD
  // ================================================

  const { data: meeting, error: fetchError } = await supabase
    .from('virtualmeetingschedulesandlinks')
    .select('*')
    .eq('_id', virtualMeetingId)
    .single();

  if (fetchError || !meeting) {
    console.error(`[calendar-automation:process] Failed to fetch virtual meeting:`, fetchError);
    throw new ValidationError(`Virtual meeting not found: ${virtualMeetingId}`);
  }

  const meetingRecord = meeting as unknown as VirtualMeetingRecord;

  // ================================================
  // STEP 3: VALIDATE RECORD
  // ================================================

  validateVirtualMeetingRecord(meetingRecord);

  console.log(`[calendar-automation:process] Validated meeting: ${meetingRecord['guest name']} & ${meetingRecord['host name']}`);

  // ================================================
  // STEP 4: NORMALIZE DATES TO ISO 8601
  // ================================================

  const startTime = validateDateTime(meetingRecord['booked date']);
  const endTime = validateDateTime(meetingRecord['end of meeting']);

  console.log(`[calendar-automation:process] Normalized dates - Start: ${startTime}, End: ${endTime}`);

  // ================================================
  // STEP 5: CREATE TEAM CALENDAR EVENT WITH MEET LINK
  // ================================================

  console.log('[calendar-automation:process] Step 5: Creating team calendar event with Meet link');

  const calendarService = new GoogleCalendarService();

  const teamCalendarId = Deno.env.get('GOOGLE_TEAM_CALENDAR_ID') || 'primary';
  const teamEventSummary = `Virtual Meeting between Split Lease, ${meetingRecord['guest name']} and ${meetingRecord['host name']}`;
  const teamEventDescription = `This is the event generated by automation. The Google Meet link is shared with ${meetingRecord['guest name']} (${meetingRecord['guest email']}) and ${meetingRecord['host name']} (${meetingRecord['host email']}).`;

  const teamEvent = await calendarService.createEventWithMeet({
    calendarId: teamCalendarId,
    summary: teamEventSummary,
    description: teamEventDescription,
    startTime,
    endTime,
    timeZone: 'America/New_York',
  });

  console.log(`[calendar-automation:process] Created team event: ${teamEvent.id}`);

  // ================================================
  // STEP 6: EXTRACT MEET LINK
  // ================================================

  console.log('[calendar-automation:process] Step 6: Extracting Meet link');

  const meetLink = calendarService.extractMeetLink(teamEvent);

  console.log(`[calendar-automation:process] Extracted Meet link: ${meetLink}`);

  // ================================================
  // STEP 7: UPDATE VIRTUAL MEETING WITH MEET LINK
  // ================================================

  console.log('[calendar-automation:process] Step 7: Updating virtual meeting with Meet link');

  const update1: VirtualMeetingUpdate = {
    'meeting link': meetLink,
    team_calendar_event_id: teamEvent.id,
    calendar_status: 'meet_link_created',
  };

  const { error: update1Error } = await supabase
    .from('virtualmeetingschedulesandlinks')
    .update(update1)
    .eq('_id', virtualMeetingId);

  if (update1Error) {
    console.error(`[calendar-automation:process] Failed to update meeting link:`, update1Error);
    throw new SupabaseSyncError(`Failed to update meeting link: ${update1Error.message}`);
  }

  console.log(`[calendar-automation:process] Updated meeting with Meet link and status: meet_link_created`);

  // ================================================
  // STEP 8: CREATE GUEST CALENDAR EVENT
  // ================================================

  console.log('[calendar-automation:process] Step 8: Creating guest calendar event');

  const serviceCalendarId = Deno.env.get('GOOGLE_SERVICE_CALENDAR_ID') || 'primary';
  const guestEventSummary = `Virtual Meeting between ${meetingRecord['guest name']}, Split Lease and ${meetingRecord['host name']}`;

  const guestEvent = await calendarService.createEventWithExistingMeet({
    calendarId: serviceCalendarId,
    summary: guestEventSummary,
    location: meetLink,
    startTime,
    endTime,
    attendees: [
      {
        email: meetingRecord['guest email'],
        responseStatus: 'accepted',
      },
    ],
    timeZone: 'America/New_York',
    sendUpdates: 'none', // Service account limitation - cannot send emails
  });

  console.log(`[calendar-automation:process] Created guest event: ${guestEvent.id}`);

  // ================================================
  // STEP 9: CREATE HOST CALENDAR EVENT
  // ================================================

  console.log('[calendar-automation:process] Step 9: Creating host calendar event');

  const hostEventSummary = `Virtual Meeting between ${meetingRecord['host name']}, Split Lease and ${meetingRecord['guest name']}`;

  const hostEvent = await calendarService.createEventWithExistingMeet({
    calendarId: serviceCalendarId,
    summary: hostEventSummary,
    location: meetLink,
    startTime,
    endTime,
    attendees: [
      {
        email: meetingRecord['host email'],
        responseStatus: 'accepted',
      },
    ],
    timeZone: 'America/New_York',
    sendUpdates: 'none', // Service account limitation - cannot send emails
  });

  console.log(`[calendar-automation:process] Created host event: ${hostEvent.id}`);

  // ================================================
  // STEP 10: UPDATE VIRTUAL MEETING WITH EVENT IDS AND FLAGS
  // ================================================

  console.log('[calendar-automation:process] Step 10: Updating virtual meeting with event IDs');

  const now = new Date().toISOString();
  const update2: VirtualMeetingUpdate = {
    guest_calendar_event_id: guestEvent.id,
    host_calendar_event_id: hostEvent.id,
    'invitation sent to guest?': true,
    'invitation sent to host?': true,
    'guest_invite_sent_at': now,
    'host_invite_sent_at': now,
    calendar_status: 'invites_sent',
  };

  const { error: update2Error } = await supabase
    .from('virtualmeetingschedulesandlinks')
    .update(update2)
    .eq('_id', virtualMeetingId);

  if (update2Error) {
    console.error(`[calendar-automation:process] Failed to update event IDs:`, update2Error);
    throw new SupabaseSyncError(`Failed to update event IDs: ${update2Error.message}`);
  }

  console.log(`[calendar-automation:process] Updated meeting with event IDs and status: invites_sent`);

  // ================================================
  // RETURN RESPONSE
  // ================================================

  console.log('[calendar-automation:process] Calendar automation completed successfully');

  return {
    virtualMeetingId,
    meetLink,
    teamEventId: teamEvent.id,
    guestEventId: guestEvent.id,
    hostEventId: hostEvent.id,
  };
}
